language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  sauce_connect: true
before_script:
- npm install -g bower web-component-tester
- bower install
script:
- xvfb-run wct
env:
  global:
  - secure: F35Rc86IJnDQzOM/y8SdJCA7JPSHusTdckXN4aaki4Oxemb1b1k3DmNaO1zsHzOKHLgQY1Ho2TVoL4xRM1Ayc1ZP1+124Il2+VHHzAxuo6DinJAL1fC7dpl0s90EYX3nNFot8/aFHljIulHRVNSv/Nz6hydoq4dHk156/s10qX/IRf9MwEd4jdedw5NT5i3uivxOdowiI2a5xlpoSRaeJwALj9T8qhF2TSjeDbcL6xTkuL8ZsW20EKV1nU12I863Sig8riP8NXN8pCxHJ+QxcgtKyf0hNowk70E7aFuALv+27hcuGs/Ca6OizTHnAEqznUT/DRT+iSUTf4xQ84KaVhfbY20m+polhydf3+GOz3DkpwCV7CANBz4DIaLRXYo4OCiDfdysEvtGxkOuPY1061UJVX34hkCXDJzejcOi4ic4DH/h8IumjIVWtdPKBxMShsV3tO1I3wayAfzje3WQUSLaJFO+TBFavY3QN+rY8Nm0L0izdfnebPTrnlcNtckG6KFsM85yQXt5BWYxXntncZ/qdvuhjZQsFBMMz11fKSTC8ytsmFwaYCMrhzbQXuyl8M26UyFsF4m4AXFxy9vAh99WEBTg/Ad8hjtXsavR510Bq+k9Mg1p8QFosY7GFm8cjUaIbCwy5vcRoDP3ibqt7o5gIAKeaF8TokWNq6jGGo4=
  - secure: WvHQ9Kjbmlo1APaOcCxj6K5aVL+LOhtXW5wBnRzEIygbfkmPuk8W1gUAZjoDJRoxCuT5+XxqHgEKhoolCwy3It5MiK8CioO8+sa7WlBlcOXWjkg0rbQfml2fyWkSRRD/vLcZidf6hfu28O4KtQfAtIHnuybIWGlceUEpdjMHL/m+qZf4yOWttHHMzXUNCoo7hugy4QXPrkXhF2d7HP7TkPGYbqR5w9lYJLsyEM9T9Dzv1CqB/YRiOvLBEM8sTkMj0pqi41Wn/l1n7C5RbzZXQ4YzgzdfHsw6157VFfLF27w9gmpYqTQliPC/PNX1WZSPPbOPdyIhZKcztbXxvcRyrvomTN33dkoFVz3fBTbegsDQxt0sKpW/bGm2HiuPUleeZUPMCl+0h5Aw/C55dzghJmIGyNmXObH5bJvgFQXJcqzzmnO+dz4f4TsR8ejrQueqd3qaHnlxwwBXf3UAHkOQ2kZzoPxyPytgpH7rkV/FXnA+vWm2Jr9+M0FZUPmLrSR7Oyvt/ZvuvjopRWhcjbEU+PpvtVYKNFmINRvP/EM85reaq3PrtpsWraF0wYaPyJ1pFb5Gc1YEpEjwmpym6FHIqu1mCR+ORhFrkzVmaIuk/Kom/QIWOtZplZiTmf6Es/R5cb2fOr6+B3p9U/7HDVHH1nzYx2sucLCA3X7xe86w8EU=
notifications:
  email: 
   on_success: never
   on_failure: never
  slack:
    secure: JLsnun3PUyC7QZqW/Hnk2vOivC7VHKLjkQ6zmqCQzIiQ4J6s9qmKQpeChA1Y00S/IqGCK1oquYPmLru2eSq/I6+hA6fslYNxQnHEEoQjVqb8m1M1Tju9m075O5+Xe3BBTqCJGZL+mM16nHH7xDqiBVKzrMKnm+EhuSXgADhT+tSspjLY8BA+xR7NsL6CV2Oq1uPQ8oxcuVOw+Om7tcHOVH2LeIb+L73qy75Q19L8fobJOjlfWp4OvVVpmF3aXwgfknQe1vgStk7j6t0e4tzrWnBpJbQw5Eikutg/vO/ss+93yXOL1aRngF6I2ygm+uAI6AB8OlYKgrS8a9C8wEDYyok1SV+FG7P2awflRlkIpTCGdJ2pxgpBC50a6E0+FLSF+XGZpskvch4EFzpJp49AGIplvw/xm2oM6nkq3eUmFt1A5MIxCuz5f7NEQqtJj8iK2jFBGZEJ2jsBm8LD9lNnTb9OrQODYpWZ4OGRNM76/7TaT0A2uZFTpeAoj9ScKXwjdf40Z1vodvQlORZgE+JbmTZg/Cd0nSgYqDLo/K/ndloCX+dxBvcN+pve7V+qy1vHw9ApTdLeR+0NTl7VYCGVwj1Y361uDk7Kb4nlmF5o3HOsdXOlhqzHZ6p1s4tX2IeWo5Pwuu9PzZBXSz3EnOh6aBrx1vJsYW+4jHD5l6eRdM8=
